# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.cache/wt [current_project]
set_property parent.project_path D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths d:/fpga/cadr/ip [current_project]
set_property ip_output_repo d:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  D:/FPGA/cadr/lispm/uhdl/rtl/defines.vh
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/actl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/alatch.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/alu01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/aluc4.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/amem01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/busint.v
  D:/FPGA/cadr/lispm/uhdl/rtl/caddr.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/contrl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/debug.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/dram02.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/dspctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/flag.v
  D:/FPGA/cadr/lispm/uhdl/rtl/ic_74s181.v
  D:/FPGA/cadr/lispm/uhdl/rtl/ic_74s182.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/ictl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/ior.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/iram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/ireg.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/iwr.v
  D:/FPGA/cadr/lispm/uhdl/rtl/keyboard.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/l.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/lc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/lcc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/lpc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/md.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mds.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mf.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mlatch.v
  D:/FPGA/cadr/lispm/uhdl/rtl/mmc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/mmc_block_dev.v
  D:/FPGA/cadr/lispm/uhdl/rtl/mmc_wrapper.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mmem.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mo01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/mouse.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/mskg4.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/npc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/null_ram_controller.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/olord1.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/olord2.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/opcd.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/opcs.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_16kx49ram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_1kx24dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_1kx32dpram_a.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_1kx32dpram_p.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_21kx32dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_2kx17dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_2kx5dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_32x19dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_32x32dpram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_32x32prom_maskleft.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_32x32prom_maskright.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_32x8prom.v
  D:/FPGA/cadr/lispm/uhdl/rtl/part_512x49prom.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/pctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/pdl01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/pdlctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/pdlptr.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/platch.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/prom01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/ps2.v
  D:/FPGA/cadr/lispm/uhdl/rtl/ps2_send.v
  D:/FPGA/cadr/lispm/uhdl/rtl/ps2_support.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/q.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/qctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/scancode_convert.v
  D:/FPGA/cadr/lispm/uhdl/rtl/scancode_rom.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/shift01.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/smctl.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/source.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/spc.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/spclch.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/spcw.v
  D:/FPGA/cadr/lispm/uhdl/rtl/iraml/spy0.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/spy124.v
  D:/FPGA/cadr/lispm/uhdl/rtl/spy_port.v
  D:/FPGA/cadr/lispm/uhdl/rtl/support.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/trap.v
  D:/FPGA/cadr/lispm/uhdl/rtl/uart.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vctl1.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vctl2.v
  D:/FPGA/cadr/lispm/uhdl/rtl/vga_display.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vma.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vmas.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vmem0.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vmem12.v
  D:/FPGA/cadr/lispm/uhdl/rtl/cadr/vmemdr.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_disk.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_io.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_ram.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_spy.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_tv.v
  D:/FPGA/cadr/lispm/uhdl/rtl/xbus_unibus.v
  D:/FPGA/cadr/lispm/uhdl/tb/cadr_unit.v
}
set_property file_type Verilog [get_files D:/FPGA/cadr/lispm/uhdl/rtl/defines.vh]
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc -mode out_of_context D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_16kx49ram/new/part_16kx49ram_ooc.xdc
set_property used_in_implementation false [get_files D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_16kx49ram/new/part_16kx49ram_ooc.xdc]

read_xdc -mode out_of_context D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_21kx32dpram/new/part_21kx32dpram_ooc.xdc
set_property used_in_implementation false [get_files D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_21kx32dpram/new/part_21kx32dpram_ooc.xdc]

read_xdc -mode out_of_context D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_1kx24dpram/new/part_1kx24dpram_ooc.xdc
set_property used_in_implementation false [get_files D:/FPGA/cadr/projects/uhdl_zynq/uhdl_zynq.srcs/part_1kx24dpram/new/part_1kx24dpram_ooc.xdc]


synth_design -top cadr_unit -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cadr_unit.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cadr_unit_utilization_synth.rpt -pb cadr_unit_utilization_synth.pb"
